<div class="row">

	<div class="col-md-12">

		<div class="col-md-12">
			<?php View::content() ?>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<?php print Form::open(); ?>
					<div class="form-group">
						<label for="password">Password</label>
						<?php print Form::pass('user.password', "class='form-control'") ?>
					</div>

					<div class="form-group">
						<label for="repassword">Password de nuevo</label>
						<?php print Form::pass('user.repassword', "class='form-control'") ?>
					</div>

					<div class="form-group">
						<?php echo Form::submit('Modificar Password', "class='btn btn-primary'"); ?>
					</div>
				<?php print Form::close() ?>
			</div>
		</div>
	</div>
</div>