<div class="form-group">
	<label for="user">Usuario</label>
	<?php print Form::text('user.user', "class='form-control'") ?>
</div>

<div class="form-group">
	<label for="password">Password</label>
	<?php print Form::pass('user.password', "class='form-control'") ?>
</div>

<div class="form-group">
	<label for="repassword">Password de nuevo</label>
	<?php print Form::pass('user.repassword', "class='form-control'") ?>
</div>

<div class="form-group">
	<label for="rol">Rol</label>
	<?php print Form::dbSelect('user.rol_id', null, null, 'Roles', "class='form-control'") ?>
</div>

<div class="form-group">
	<?php echo Form::submit($submitButton, "class='btn btn-primary'"); ?>
</div>