<div class="jumbotron">
	<h1 class="text-center">Boilerplate de WebApps en Kumbiaphp</h1>
	<h2>Configuración inical que incluye Sistema de navegación, Sass con Bootrap por defecto, bower, grunt para comprimir los archivos .js, Sistema de usuarios y permisos entro otros.</h2>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>Distribució en github</h3>
			</div>
			<div class="panel-body">
				<p>Puedes encontrar esta distribución en <?php print Html::link('https://github.com/gbelot2003/sistema-kumbiaphp', 'Github') ?>
				Sirvete descargarla y modificarla a placer y si puedes y tienes tiempo, enviame los merge que consideres necesarios.</p>
				<p>Tambien puedes encontrarlos en Bitbucket si asi lo prefieres en <?php print Html::link('', 'Bitbuket') ?></p>
				<p>Quedo pendiente de subir un par de videotutoriales a youtube</p>
				<p>"have a fun codding ;)"</p>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>Utilíza rvm y nvm de preferencia</h3>
			</div>
			<div class="panel-body">
				<p>Para evitar conflictos y quebraderos de cabeza con ruby y node, deberias usar rvm y nvm.</p>
				<p>Con rvm puedes luego instalar el gem bundler y luego iniciar los archivos de sass</p>
				<p>y con nvm, podras instalar los archivos del package.js y bower.js sin problemas de compatibilidad (utilizo node v0.10.33)</p>
			</div>
		</div>
	</div>

</div>
