<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<?php print Html::link('', 'Sistema', "class='navbar-brand'") ?>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="<?php print $navActive['inicio'] ?>"><?php print Html::link('', 'inicio') ?></li>
			</ul>

			<?php if(!isset($user)){ ?>
			<ul class="nav navbar-nav navbar-right">
				<li class="<?php print $navActive['login'] ?>">
					<?php print Html::link('login', 'Login') ?>
				</li>
			</ul>

			<?php } else { ?>
			<ul class="nav navbar-nav navbar-right">
				<li><?php print html::link('', Auth::get('user')); ?></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Configuraciones <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><?php print	Html::link('user/', 'Usuarios y roles'); ?></li>
						<li class="divider"></li>
						<li><?php print Html::link('logout', 'Logout') ?></li>
					</ul>
				</li>
			</ul>
			<?php } ?>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>